create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  source_page text not null check (source_page in ('index-1', 'index-2', 'index-3')),
  path text,
  referrer text,
  user_agent text,
  device_type text check (device_type in ('desktop', 'tablet', 'mobile')),
  country text,
  region text,
  city text,
  ip_hash text
);

alter table public.page_views enable row level security;

drop policy if exists "admin can read page views" on public.page_views;
create policy "admin can read page views"
on public.page_views
for select
to authenticated
using ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin');

create index if not exists page_views_created_at_idx on public.page_views (created_at desc);
create index if not exists page_views_source_created_idx on public.page_views (source_page, created_at desc);
create index if not exists page_views_geo_idx on public.page_views (country, region, city);
