create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  source_page text not null,
  source_path text,
  company_name text not null,
  manager_name text not null,
  position text not null,
  phone text not null,
  request_type text not null,
  memo text,
  privacy_agreed boolean not null default false,
  status text not null default '신규',
  admin_note text not null default ''
);

alter table public.inquiries enable row level security;

drop policy if exists "public insert inquiries" on public.inquiries;
create policy "public insert inquiries"
on public.inquiries
for insert
to anon, authenticated
with check (
  privacy_agreed = true
  and status = '신규'
  and admin_note = ''
);

drop policy if exists "admin read inquiries" on public.inquiries;
create policy "admin read inquiries"
on public.inquiries
for select
to authenticated
using ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin');

drop policy if exists "admin update inquiries" on public.inquiries;
create policy "admin update inquiries"
on public.inquiries
for update
to authenticated
using ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin')
with check ((auth.jwt() -> 'user_metadata' ->> 'role') = 'admin');

create index if not exists inquiries_created_at_idx on public.inquiries (created_at desc);
create index if not exists inquiries_source_page_idx on public.inquiries (source_page);
create index if not exists inquiries_status_idx on public.inquiries (status);
